### ISSUE TITLE
Doesn't like tables with spaces

### ISSUE THREAD

**Issue by hughc** [sleiman/airtable-php#10]
Thanks for these wrapper classes. 

I was struggling to get even the most straightforward 'retrieve all records in a table' working, until I did rawURLEncode on the `$request` string:

`$curl = curl_init($this->airtable->getApiUrl(rawurlencode($request)));`

My table name has spaces (and a colon) in it, passing it raw was returning am empty response.

**Comment by sleiman** [comment]
Can you give me more details on your case? I can try to improve the script.

**Comment by hughc** [comment]
(sorry, hit submit a bit prematurely there)

**Comment by sleiman** [comment]
Good to know, thanks for your feedback! I'll see what I can do.

**Comment by hughc** [comment]
on closer examination, rawurlencoding the whole request string can break offsets; it's just the table name that needs it.

**Comment by sleiman** [comment]
@hughc  this was fixed, thank you

**Comment by hughc** [comment]
was the fix pushed?

**Comment by sleiman** [comment]
Hey @hughc I thought this was fixed in the last push by apparently it wasn't. We will look into it now, should be fixed by tomorrow. Thank you!

**Comment by glaliberte** [comment]
It's now fixed with latest push
