### ISSUE TITLE
Getting all rows where checkbox is not checked

### ISSUE THREAD

**Issue by mlordi** [sleiman/airtable-php#17]
How would I go about getting all rows where a checkbox is false? I have tried the following with no success.

```
$params = array(
		"filterByFormula" => "AND ( Task_Written == FALSE )"
	);

$request_items = $airtable->getContent( 'Invoice Items', $params );
$response_items = $request_items->getResponse();
```

**Comment by glaliberte** [comment]
Hi,

Can you try using Logical functions TRUE() and FALSE() instead of FALSE?

In your AND condition, you are comparing it to FALSE instead of FALSE().

**Comment by glaliberte** [comment]
Also, in AirTable, equal to comparaisons are using only one equal sign (=).

You can always check the following documentation as reference :
https://support.airtable.com/hc/en-us/articles/203255215-Formula-field-reference#logical

**Comment by mlordi** [comment]
Thanks much for this information. I am just digging into airtable and am a newbie. This API is a great help though. Thanks for the quick response.

**Comment by mlordi** [comment]
So I did update the code to use = FALSE() and my code is still not executing all unchecked boxes.

```
$params = array(
		"filterByFormula" => "AND ( Task_Written = FALSE() )"
	);

	$request_items = $airtable->getContent( 'Invoice Items', $params );
	$response_items = $request_items->getResponse();
```

**Comment by glaliberte** [comment]
There is nothing else I can see in your formula that can be wrong, except:

- maybe the space between AND and the opening paranthese should be removed

- if you are not adding any other conditions, you should not even use the AND function, it should just be the condition

Try one of the following:

- Task_Written = FALSE()
- Task_Written = BLANK()

**Comment by mlordi** [comment]
Removing the AND did it. You rock! Updated code below.

```
$params = array(
		"filterByFormula" => "( Task_Written = FALSE() )"
	);

	$request_items = $airtable->getContent( 'Invoice Items', $params );
	$response_items = $request_items->getResponse();
```
