### ISSUE TITLE
Get data from row past 100

### ISSUE THREAD

**Issue by mlordi** [sleiman/airtable-php#18]
If I have a table that has 125 records how would I get the data from record 101 for example?
I see there is two records arrays but not sure how to access that second offset array to get my data.
Thanks in advance for the help.

**Comment by glaliberte** [comment]
The problem with those kind of API, such as Airtable, is that you need the previous page to load the next one.

Unless you know the offset parameter for the second page, you cannot tell the API :

"I want to load the third page of results"

So you need to loop through the results and gather them before manipulating them.

`$request = $airtable->getContent( 'Contacts' );

$all_entries = [];

do {
    $response = $request->getResponse();
    foreach( $response[ 'records' ] as $record )
      
}
while( $request = $response->next() );

print_r($request);`

**Comment by glaliberte** [comment]
The problem with those kind of API, such as Airtable, is that you need the previous page to load the next one.

Unless you know the offset parameter for the second page, you cannot tell the API :

"I want to load the third page of results"

So you need to loop through the results and gather them before manipulating them.

```
$request = $airtable->getContent( 'Contacts' );

$all_entries = [];

do {
    $response = $request->getResponse();
    foreach( $response[ 'records' ] as $record )
    {
        $all_entries[] = $record;
    }
}
while( $request = $response->next() );

// do something with all the entries
// eg: loop through them all again

print_r($all_entries);
```

That way, you can retrieve them from the server once and do what you need to do then.

**Comment by mlordi** [comment]
Got it, thanks again glaliberte!
