### ISSUE TITLE
Can the api write to the airtable activity comment?

### ISSUE THREAD

**Issue by mlordi** [sleiman/airtable-php#19]
Do you know if it is possible to write into the comments section of the activity area of airtable?

**Comment by glaliberte** [comment]
Hi @mlordi ,

I never heard of this idea before.

The question has been asked here before:

https://community.airtable.com/t/accessing-airtable-comments-via-api/6898

I am gonna subscribe to this thread and implement it if it ever sees the light.

**Comment by glaliberte** [comment]
However, the activity thread is being used when you use the API.

It's still saving the activity that occures. The activities will appear as the user that created the api key.
