### ISSUE TITLE
Insert into a 'link to another record' field

### ISSUE THREAD

**Issue by Yakito** [sleiman/airtable-php#22]
Hello! First, thank you very much for the library!
Does anyone know how to insert a value into a 'link to another record' field? When I try to enter by name, it complains that it is duplicated and the key cannot be duplicated (which makes sense).

Any tips will be appreciated! thanks again!

**Comment by glaliberte** [comment]
Hello @Yakito ,

The value you insert in this type of field must be an array of Airtable ids.

I don't remember very well, but I think that even when you set the option for single record on the field to true, you still need to pass an array of ids.

**Comment by Yakito** [comment]
@glaliberte Thanks a lot!
