### ISSUE TITLE
How to add Files, Images in attachment field?

### ISSUE THREAD

**Issue by siddhu09rocks** [sleiman/airtable-php#26]
First of all, amazing work and thanks a lot.. 

My question is How to add images, PDFs etc in attachment field ?

does this API got certain calls? can you point me to the right direction ?

Thanks,

**Comment by sleiman** [comment]
Hi @siddhu09rocks, thanks for your message!

The Airtable API documentation will give you all the exact parameters you need. Their documentation maps your database structure. What you are looking for is the "array of attachment objects". The only required field is "url" which in this case will be the path to your file/image or a web link where the file/image is hosted. 

It would look something like that:

```
// In this case you are adding multiple files
$images_array = array(
	array(
	 	'url' => 'path/to/file1'
	),
	array(
		'url' => 'path/to/file2'
	),
);

// Considering your field is set to "attachment" and called "Images"
$new_entry_details = array(
    'Name'        =>"Some Name",
    'Images'     => $images_array,
    'Email'       =>'email@domain.com',
);

$new_entry = $airtable->saveContent( "Contacts", $new_entry_details );

```

I hope this helps, let me know if you need more info.

**Comment by siddhu09rocks** [comment]
Hey @sleiman , Thanks a lot for reply man. 
Last one..  if i use updateContent 

Does this overwrite existing values in Airtable field? or append new files (while keeping old values/files) ?

**Comment by sleiman** [comment]
Hey @siddhu09rocks, the Airtable API will overwrite existing values.

From the Airtable API documentation:

> To add attachments to Image, add new attachment objects to the existing array. Be sure to include all existing attachment objects that you wish to retain. To remove attachments, include the existing array of attachment objects, excluding any that you wish to remove.

**Comment by chivocarc** [comment]
I know this is like a year old but just in case if you want to add more attachments to the existing ones, get your previous content and just add it to your attachment array
```
// In this case you are adding multiple files
$images_array = array(
	array(
	 	'url' => 'path/to/file1'
	),
	array(
		'url' => 'path/to/file2'
	),
);

// Get your content
$request = $airtable->getContent("Contact/$record_id");
$response = $request->getResponse();
$record = $response['fields'];

// If there is attachments, annex them to your array
if ( $record->Images ) {
	$images = $record->Images;
	foreach ($images as $value) {
		$images_array [] = $value;
	}
}

// Considering your field is set to "attachment" and called "Images"
$update_details= array(
    	'Images' => $images_array,
);

$update= $airtable->updateContent( "Contacts/$record_id", $update_details );
```

**Comment by jatniel** [comment]
Hi, if in the array, that id has no image.
How can we avoid an error and save the content without image?
