### ISSUE TITLE
Specify number of rows to fetch and/or type of view

### ISSUE THREAD

**Issue by jjokham** [sleiman/airtable-php#29]
Hi,
Can you give example to just fetch one row or specify the number of rows. Also, how to pass view as a parameter similar to airtable API.

**Comment by sleiman** [comment]
@jjokham Here's an example that shows a few params you can pass. You can use pageSize or maxRecords to get on record per request. The example shows how to use a view, just pass the name in the "view" param. Let me know if this helps. 

```
$params = array(
    "filterByFormula" => "OR(FIND('{$spotify_user}', User) > 0)",
    "sort" => array(array('field' => 'End', 'direction' => "desc")),
    "maxRecords" => 1,
    "pageSize" => 50,
    "view" => "Name of your View"
);

$request = $airtable->getContent( 'Contacts', $params);

do {
    $response = $request->getResponse();
    var_dump( $response[ 'records' ] );
}
while( $request = $response->next() );
```
