### ISSUE TITLE
field names with spaces

### ISSUE THREAD

**Issue by ezitsolutions** [sleiman/airtable-php#30]
How do you get field names with spaces?  I keep getting errors.

**Comment by sleiman** [comment]
How are you trying to access the fields?

This is an example:
```
$spotify_id  = $track_details->fields->{'Spotify ID'};
```

Let me know if it helps

**Comment by ezitsolutions** [comment]
Thank you for the quick reply - that did it.  Been staring at it too long, guess I just needed another pair of eyes on it.  Thanks!
