### ISSUE TITLE
Update multiple entries

### ISSUE THREAD

**Issue by Pfaufisch** [sleiman/airtable-php#31]
Is there a suggested way to update multiple entries at once? I'm currently using a foreach loop and it seems to work, but I'm not sure if that's the best way and if I will run into the rate limit? Just passing the arrays doesn't seem to work.

$updateDetails = [ ... my data ... ];
$updateRecords = [ ... records i want to update ... ];

$i = 0;
    foreach ($updateRecords as $updateRecord) {
    $update = $airtable->updateContent($updateRecords[$i], $updateDetails[$i]);
    $i++;
};

**Comment by glaliberte** [comment]
Hi @Pfaufisch ,

Airtable doesn't support updating multiple records at once.

I am checking to merge https://github.com/sleiman/airtable-php/pull/35 to support rate limiting as well.

Hope this will fix things for you.

**Comment by Pfaufisch** [comment]
My solution has been working fine so far, though it has been used only occasionally. And it's not really fast. Airtable is also adding batch functionality, but I'm not sure if it's already available for all users. Adding #35 seems to be a good idea anyway.

**Comment by glaliberte** [comment]
Thank you for the insight.

I requested a Beta access for the batch API feature so I can add support for it soon.

**Comment by glaliberte** [comment]
Batch API support has been added and is now available to use in v2.3.0.
