### ISSUE TITLE
Pound sign(£) removed from field name 

### ISSUE THREAD

**Issue by bikashkhatri** [sleiman/airtable-php#38]
For a field name with Pound Sign(£), the response is returning a field name with no pound sign. My request data is:
`$data = array(
            "Total Value - £" => 200
        );`

For which I get an error message:
` "Unknown field name: "Total Value - ""`

**Comment by sleiman** [comment]
Hey @bikashkhatri  I just tried with a column name containing a pound sign, it worked fine. Let me know if you were able to resolve your problem without having to remove the (£) from the name.

**Comment by bikashkhatri** [comment]
@sleiman I was using Laravel tinker to make the request. Tinker CLI wasn't taking the (£) pound sign. I tried it again by creating a route and it works! So my request data had no pound sign. I realized that.
