### ISSUE TITLE
ErrorException: count() - quickCheck method

### ISSUE THREAD

**Issue by tjimenez** [sleiman/airtable-php#40]
ErrorException: count(): Parameter must be an array or an object that implements Countable in ~/vendor/sleiman/airtable-php/src/Airtable.php:136

```
$check = $airtable->quickCheck("Table", "QR Code", $profile->qr_code);

                if( $check->count > 0 )
```

**Comment by glaliberte** [comment]
Hi @tjimenez ,

We made a fix on the quickCheck method.

Let me know if it still doesn't fix the issue.

Thanks,
Guillaume

**Comment by tjimenez** [comment]
Thanks I'll check.
