### ISSUE TITLE
syntax for use

### ISSUE THREAD

**Issue by ari14850** [sleiman/airtable-php#41]
There are some inconsistencies in the syntax between the samples and the downloads. I am attempting this code
<img width="509" alt="Screen Shot 2020-08-19 at 1 13 37 PM" src="https://user-images.githubusercontent.com/33635701/90668586-50294680-e21e-11ea-86b3-45a8e9106f53.png">

and the echo for "new array" is never executing leading me to believe there is an issue with the $airtable variable declaration.

the use command is sometimes shown as

use TANIOS\Airtable

and sometimes

use \TANIOS\Airtable 

so I'm not sure if this could be related.

**Comment by KillianLeroux** [comment]
Hi ari, check your PHP Errors (enable them in php.ini: https://www.php.net/manual/en/function.error-reporting.php).

And check your curl request, for that I add ```var_dump(curl_getinfo($curl));``` in `vendor/sleiman/airtable-php/src/Request.php` at the end of `init()` function.

You can also use a `try/catch`:

```
try {
    $airtable = new Airtable(...);
} catch (\Throwable $th) {
     var_dump($th->getCode());
     var_dump($th->getMessage());
     var_dump($th->getTraceAsString());
}
```

**Comment by ari14850** [comment]
thanks!

 error reporting is set to
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

but it isn't showing up in the erro log. I have "echo" commands at various parts of the script and it just keeps quitting and the echo for "newarray" shown above just never outputs.

I still don't get why the TANIOS sometimes has the slash in front and sometimes not

**Comment by sleiman** [comment]
Hey @ari14850 would you like to get on a quick screnshare? I can help you figure it out. You can email me sleiman at tanios dot ca
