### ISSUE TITLE
Problems with accents

### ISSUE THREAD

**Issue by KillianLeroux** [sleiman/airtable-php#42]
Hi!

First of all: thanks for your project ;)

I have a problem when I use tab names with accents, example:

```
$params = [
    'maxRecords' => 30,
    'view' => 'myView'
];

$relations = [
    'Métier' => rawurlencode('Types de métier'),
    'Ecosystème' => 'Ecosystème'
];

$companiesAT = $airtable->getContent('myTable', $params, $relations)->getResponse();
```

As you can see I have to apply `rawurlencode` on tab name to work ("Types de métier" works, "Ecosystème" doesn't work).
The field with accents work ("Métier" for example).

Maybe same problem with other elements like db name (I don't test them for now).

I think we have to proceed here:

```
if( ! $this->is_post || strtolower( $this->is_post ) === 'delete' )
{
    if (!empty($this->data)) {
        // rawurlencode or replace accents
        $data = http_build_query($this->data);
        $request .= "?" . $data;
    }

    $url_encoded = true;
}
````

in `init()` function in `Request.php`.

**Comment by glaliberte** [comment]
Hi @KillianLeroux ,

I just pushed a fix to support table names with accents.

Hope this helps :)

Thanks,
Guillaume

**Comment by KillianLeroux** [comment]
Wonderful it works!

Thanks <3
