### ISSUE TITLE
Check if Airtable is down

### ISSUE THREAD

**Issue by bquimper** [sleiman/airtable-php#46]
Hi,

I love the wrapper, good job! Twice this week Airtable was down and both times it wrecked my system sitting on top of it.

Is there a way to validate if Airtable is up before I start pulling data from the API?

Thanks,
Ben

**Comment by glaliberte** [comment]
@bquimper I think you can handle this situation with a little Try Catch. We can't prevent errors from happening especially when they are not in our control.
