### ISSUE TITLE
Help - Multiple column search

### ISSUE THREAD

**Issue by ilearnbydoing** [sleiman/airtable-php#48]
any idea how to search with multiple columns? unlike just single column lookup in QuickCheck()

**Comment by sleiman** [comment]
Hi, you can read this section of the Readme
https://github.com/sleiman/airtable-php#use-params-to-filter-sort-etc

Simple
` "filterByFormula" => "AND( Status = 'New' )",`

More complex
`"filterByFormula" => "AND({Page} = '$page',{Content Status}= 'Live', FIND( '$user_status', {User Status} )>0 )",`


Let me know if this answers your question
