### ISSUE TITLE
PHP 8.1 compatibility (ReturnTypeWillChange)

### ISSUE THREAD

**Issue by samnabi** [sleiman/airtable-php#49]
Getting this error when using PHP 8.1:

```
Return type of TANIOS\Airtable\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Request.php:148
```

**Comment by robiningelbrecht** [comment]
same issue here, unusable with PHP8.1

**Comment by glaliberte** [comment]
hi @robiningelbrecht  and @samnabi , we are working toward supporting PHP 8.1. This is our priority. We will let you know when we update the package.

**Comment by glaliberte** [comment]
@robiningelbrecht Package has been updated. Use Version 3.0.0 for PHP 8.1 support.
