### ISSUE TITLE
Not all records returned

### ISSUE THREAD

**Issue by HeadStudios** [sleiman/airtable-php#60]
Please provide input on why the following code:

$records = $airtable->getContent( 'Contact');
 return $records->getResponse();

Would not return all the records in the Contact table and some possible reason for this issue. Thank you!

**Comment by sleiman** [comment]
Hi @HeadStudios, how many records are you getting vs expecting? Are you using the pagination?

**Comment by HeadStudios** [comment]
> Hi @HeadStudios, how many records are you getting vs expecting? Are you using the pagination?

Please elaborate on pagination and how I can implement it to ensure I get at least 500 records - my estimate is I am getting 150 records and should be getting at least twice that.

**Comment by HeadStudios** [comment]
My Contact table has 1,510 records - https://share.getcloudapp.com/7KujPKB5

Return from following function called from my Laravel route:
`public function getRecords() {
        $airtable = $this->airtable;
        

        $params = array(
            "view" => "Freezer",
            "maxRecords" => 800
        );
        
        $records = $airtable->getContent( 'Contact');
        return $records->getResponse();
    }`

As you can see Email column only returns around 300 entires - https://share.getcloudapp.com/6quN8q9l

Filtering to only show records where Email column is not empty - https://share.getcloudapp.com/GGuJQGZQ

As you can see there is a large discrepancy between total records with Email and those returned from my PHP - any input into potential reasons for the discrepancy would be much apprecaited.

Thank you!



This is the result of

**Comment by HeadStudios** [comment]
Note: I have just updated code as follows:

`public function getRecords() {
        $airtable = $this->airtable;
        

        $params = array(
            "view" => "All",
            "maxRecords" => 800
        );
        
        $records = $airtable->getContent( 'Contact');
        return $records->getResponse();
    }`

However the result is the same: 

https://share.getcloudapp.com/9ZuzxZG4

Any input into what seems like potential throttling of the max results returned would be much appreciated.

Thank you!

**Comment by sleiman** [comment]
If you look at our documentation you will see this example:
```
// You don't have to use all the params, they are added as a reference
$params = array(
    "filterByFormula" => "AND( Status = 'New' )",
    "sort" => array(array('field' => 'Count', 'direction' => "desc")),
    "maxRecords" => 175,
    "pageSize" => 50,
    "view" => "Name of your View"
);

$request = $airtable->getContent( 'Contacts', $params);

do {
    $response = $request->getResponse();
    var_dump( $response[ 'records' ] );
}
while( $request = $response->next() );

print_r($request);
```
This will allow you to loop through all the pages and retrieve all the records.

Let me know if this helps

-- 

From the Airtable API documentation:

Pagination
The server returns one page of records at a time. Each page will contain `pageSize` records, which is 100 by default.

If there are more records, the response will contain an `offset`. To fetch the next page of records, include `offset ` in the next request's parameters.

Pagination will stop when you've reached the end of your table. If the `maxRecords ` parameter is passed, pagination will stop once you've reached this maximum.

**Comment by HeadStudios** [comment]
Thank you will review and attempt now - this all makes sense - appreciate your clarification.

**Comment by HeadStudios** [comment]
Can confirm this has worked for me, appreciate it and am closing this issue
