### ISSUE TITLE
Comment on Token

### ISSUE THREAD

**Issue by HeadStudios** [sleiman/airtable-php#61]
From visiting the Developer section in AirTable I have noticed they are stating that API keys will no longer be used in the future and they are switching to Tokens - are you able to provide any input on the compatibility of airtable-php with this new Token architecture?

**Comment by bill-k-cinobo** [comment]
They have started sending out emails about that currently:

- August 1st, 2023: Users will no longer be able to create new API keys

- February 1st, 2024 (next year): Existing API keys cannot be used to access the Airtable API


Do you think this is something airtable-php will cover in the near future or not?

**Comment by HeadStudios** [comment]
> They have started sending out emails about that currently:
> 
> * August 1st, 2023: Users will no longer be able to create new API keys
> * February 1st, 2024 (next year): Existing API keys cannot be used to access the Airtable API
> 
> Do you think this is something airtable-php will cover in the near future or not?

hey it's no bigger I just pass the token and it works fine :)
