### ISSUE TITLE
new API authentication methods

### ISSUE THREAD

**Issue by regisgrison** [sleiman/airtable-php#64]
Hi,

I just received an email from Airtable saying we are using a legacy API Key.

Do you plan to support the new authentication methods?

Here is the announcement: [https://community.airtable.com/t5/announcements/new-api-capabilities-now-in-ga-and-upcoming-api-keys-deprecation/ba-p/141824](https://community.airtable.com/t5/announcements/new-api-capabilities-now-in-ga-and-upcoming-api-keys-deprecation/ba-p/141824)

Regards.

**Comment by cy-josh** [comment]
The new authentication will work as-is. https://github.com/sleiman/airtable-php/issues/58#issuecomment-1580296499

**Comment by regisgrison** [comment]
Oh! Great!

I looked in issues but did not see that one.

Thank you.
