### ISSUE TITLE
Php version issue.

### ISSUE THREAD

**Issue by shamshashmi** [sleiman/airtable-php#9]
Hi sleiman...

**Comment by sleiman** [comment]
Hi!

**Comment by shamshashmi** [comment]
leiman/airtable-php 2.0.1 requires php ^5.3.3 || ^7.1 -> your PHP version (7.0.3) does not satisfy that requirement.
I'm having this issue. on some machinges... i think should work with atleast 7.0

**Comment by shamshashmi** [comment]
can please check the min requirements?

**Comment by sleiman** [comment]
There's a PHP version error when installing from composer. It's the packagist update that's not detecting my update. Let me see what I can do now.

**Comment by shamshashmi** [comment]
Yes please make it possible to install on atleast php 7.0

**Comment by sleiman** [comment]
@shamshashmi sorry about the delay, this was fixed!
